### PR TITLE
Firefox WebExtension support

### PR DESCRIPTION
**Pull request by encounter**
A few things of note:

- Converted jshint configuration to eslint to support ES2017 features (async/await)
- I had to resort to a nasty hack to get Polymer elements working properly when created from the extension. I'll look into cleaning this up or finding a different approach.
- Using fetch instead of XMLHttpRequest since FF was trying to parse the CSS as XML. (And it simplifies that code a lot)
- There are some styling issues that aren't present on Chrome and would need to be investigated. A couple I noticed were the main background and hover color of the progress bar.

### CODE REVIEW

**Comment by chrisxclash** [comment]
Whew, appreciate you taking all this on. I'm already in love with your eslint/fetch changes since I've been using those at work. 

By chance could you point me in the right direction for getting this guy up and running? I sadly haven't taken the time to look into Firefox development in the last year or two and I'm sure a ton has changed. Thanks again for working on this!

**Comment by encounter** [comment]
I've been using about:debugging to load the folder as a temporary extension (like Chrome's "Load unpacked extension"). Then you'll want to use the Debug option that shows up, since content script errors show up there instead of the Play Music page's console.

**Comment by chrisxclash** [comment]
I just released version 3.0.0, which is a complete rewrite. I've peeked into the Firefox stuff a little bit, which actually works almost perfectly out of the box, with a few caveats.

- chrome.runtime api - Firefox uses promises, Chrome uses callbacks. There's a dumb polyfill you can use to convert Chrome to use promises which I feel gross about using. I also made a hacky polyfill myself that seems to work, but should probably be better tested. I'll probably push up a `feature/firefox` branch or something with this a bit.
- Accented Favicon - This one's a mystery to me. There's something going on on the background page, I'm guessing related to CORS. There's no issues being throw in either console, but it seems that Firefox is preventing the image from loading on the canvas, so it just renders a white square.
- Homepage panels - These aren't keeping the correct color when scrolling, but I didn't get a chance to look into them yet.

Other than those few issues, it's looking really promising! If you wanna poke around a bit and see if you can find any other stuff, I'd definitely appreciate the help. I don't use Firefox as a daily driver so I haven't had as much of a chance to dig in yet with doing all the Chrome rewrite.

Appreciate the help. 👍

**Comment by encounter** [comment]
Great! I'll open a new PR if I get a chance to poke around at it.

**Pull request closed without merging**
