### PR TITLE
Fixes for dark default album art

### PR DESCRIPTION
**Pull request by firstEncounter**
This fixes support for dark album art for places other than album cards, and also inverts the queue background when playing a song with no art. ([Before](http://i.imgur.com/tLi374d.png), [after](http://i.imgur.com/Puj2VYD.png))

Also included are a couple of unrelated fixes, which I can remove if you'd like.

### CODE REVIEW

**Comment by chrisxclash** [comment]
Looks good! It's hard to find all the small stuff sometimes, haha.

Also, thanks for finding those random errors for me. I'll get everything put in sometime in the next day or so!

**Comment by Dragory** [comment]
Hey, good thing you caught this! I also noticed (late!) that the img selectors I added in my previous pull request were way too specific (indeed, why restrict them to cards?).

Related to this, there are some similar issues with the dark buttons as well (the dark theme doesn't get applied if the button doesn't have the class .button; there are a couple buttons like that somewhere). I'll prob send a pull request about that soon after making sure it doesn't break anything.

**Comment by chrisxclash** [comment]
@Dragory I'm actually in the works of getting all this stuff gathered up before I push it up. Which areas did you see the messed up buttons on by chance?

I know there were a few in the playlist creation for a while that I had to fix, but I wasn't sure where else you saw them.

**Comment by Dragory** [comment]
@chrisxclash I'm not actually sure anymore, just noticed some a few days ago. They were somewhere pretty "hidden", but that might've been the playlist creation buttons you mentioned. If I notice any white buttons after the next update, I'll fix them and make a pull request for it!

**Comment by chrisxclash** [comment]
Alright, I tried to find any issues with buttons and went ahead and fixed a few. Let me know if any others show up!

@firstEncounter Got all your changes in there, thanks again, bud!

**Pull request closed without merging**
